---
argument_specs:
  main:
    short_description: Role to fetch PRC data from Instana
    description:
      - This role runs a Python script to fetch Probable Root Cause (PRC) data from Instana
      - The JSON output is stored as a job artifact in AWX
    options:
      instana_api_token:
        type: str
        required: true
        description: Instana API token for authentication