---
- name: Manage PRC Label
  hosts: localhost
  connection: local
  gather_facts: true
  
  tasks:
    - name: Include PRC Label role
      include_role:
        name: prc_label
      when: action == "run"
      tags:
        - prc_label

# Made with Bob
