---
- name: Manage Remediation for PRC Incidents
  hosts:
    - environment
  gather_facts: true
  
  # This playbook can be run with an optional incident_id parameter to filter for a specific incident
  # Example: ansible-playbook manage_remediation.yaml -e "incident_id=23"
  # Currently supported incident IDs: 3, 23
  
  pre_tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - instana_api_token is defined
        fail_msg: "instana_api_token is required. This should be provided securely via AWX credentials."
        success_msg: "All required variables are defined"
      tags:
        - always

  tasks:
    - name: Import Remediation role
      ansible.builtin.import_role:
        name: ../roles/remediation
      vars:
        instana_api_token: "{{ instana_api_token }}"
        incident_id: "{{ incident_id | default(omit) }}"
      tags:
        - manage_remediation

