---
- name: Manage Alerts - Disable Enabled Alerts
  hosts:
    - environment
  gather_facts: true

  pre_tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - base_url is defined
          - application_id is defined
          - instana_api_token is defined
        fail_msg: "base_url, application_id, and instana_api_token are required variables."
        success_msg: "All required variables are defined"
      tags:
        - always
        - disable_alerts

  tasks:
    - name: Import alerts role
      ansible.builtin.import_role:
        name: ../roles/alerts
      vars:
        operation: "disable"
        base_url: "{{ base_url }}"
        application_id: "{{ application_id }}"
        instana_api_token: "{{ instana_api_token }}"
      tags:
        - manage_alerts
        - disable_alerts


