---
- name: Manage PRC Data Collection from Instana
  hosts:
    - environment
  gather_facts: true
  
  
  pre_tasks:

    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - instana_api_token is defined
          - incident_id is defined
        fail_msg: "instana_api_token and incident_id are required. incident_id should be passed as a global variable."
        success_msg: "All required variables are defined"
      tags:
        - always

  
  tasks:
    - name: Import PRC role
      ansible.builtin.import_role:
        name: ../roles/prc
      vars:
        instana_api_token: "{{ instana_api_token }}"
        prc_incident_id: "{{ incident_id }}"


