---
- name: Check if running in AWX
  ansible.builtin.set_fact:
    is_awx: "{{ lookup('env', 'AWX_EXECUTION_ENVIRONMENT') | default('', true) != '' }}"

- name: Validate python version for local environment
  ansible.builtin.assert:
    that: "'3.12' is version_compare(ansible_facts.python_version, '<=')"
    fail_msg: "Python version for system {{ ansible_facts.python.executable }} must be 3.12 or later. Got {{ ansible_facts.python_version }}"
    success_msg: "Python version {{ ansible_facts.python_version }} (>= 3.12) is OK."
  when: not is_awx | bool

- name: Skip python version check for AWX
  ansible.builtin.debug:
    msg: "Running in AWX environment, skipping Python version check"
  when: is_awx | bool

- name: Import Helm check tasks
  ansible.builtin.import_tasks:
    file: check_helm_version.yaml

- name: Import Kubectl check tasks
  ansible.builtin.import_tasks:
    file: check_kubectl_version.yaml

- name: Import OpenShift CLI check tasks
  ansible.builtin.import_tasks:
    file: check_oc_version.yaml
